config/routes.rb
AssOne::Application.routes.draw do
  get "pages/home"

  get "pages/help"

  get "pages/contact"

  get "pages/about"

  get "pages/specifications"

  get "pages/references"

  get "pages/resources"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end

  def specifications
  end

  def references
  end

  def resources
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(curr_title)
    base_title = "ISYS100 Assignment One"
    if curr_title.empty?
      base_title
    else
      "#{base_title} | #{curr_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_content.html.erb
<content class="round">
  <div class="main_inner">
    <div class="main_top">
      <h1><%= yield(:heading) %></h1>
    </div>
    <div class="main_left">
      <%= yield %>
    </div>
    <div class="main_right">
        <%= javascript_tag 'twitter()' %>
    </div>
  </div>
</content>

app/views/layouts/_footer.html.erb
<footer class="round">
  <div class="footer_inner">
    <center>
      <%= javascript_tag 'showQuotation()' %>
    </center>
    <nav>
      <ul>
        <li><%= link_to 'iLearn', 'http://ilearn.mq.edu.au/my/' %>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><%= link_to 'Help', help_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_head.html.erb
<title><%= page_title(yield(:title)) %></title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "http://widgets.twimg.com/j/2/widget.js" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag('gir_sitting.png', alt: 'ISYS100 Assignment One', size: '100x100', class: "round") %>
  <%= link_to(logo, root_path) %>
  <nav class="round">
    <ul>
      <li><%= link_to('References', references_path) %></li>
      <li><%= link_to('Specifications', specs_path) %></li>
      <li><%= link_to('Report', report_path) %></li>
      <li><%= link_to('Home', root_path) %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
</head>
<body>
  <div class="main_box">
    <%= render 'layouts/header' %>
    <%= render 'layouts/content' %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<% provide :title, 'About'  %>
<% provide :heading, 'About'  %>
<h3>Wikileaks are a lot more interesting than me</h3>
<p>WikiLeaks is a not-for-profit media organisation. Our goal is to bring important news and information to the public. We provide an innovative, secure and anonymous way for sources to leak information to our journalists (our electronic drop box). One of our most important activities is to publish original source material alongside our news stories so readers and historians alike can see evidence of the truth. We are a young organisation that has grown very quickly, relying on a network of dedicated volunteers around the globe. Since 2007, when the organisation was officially launched, WikiLeaks has worked to report on and publish important information. We also develop and adapt technologies to support these activities.</p>
<p>WikiLeaks has sustained and triumphed against legal and political attacks designed to silence our publishing organisation, our journalists and our anonymous sources. The broader principles on which our work is based are the defence of freedom of speech and media publishing, the improvement of our common historical record and the support of the rights of all people to create new history. We derive these principles from the Universal Declaration of Human Rights. In particular, Article 19 inspires the work of our journalists and other volunteers. It states that everyone has the right to freedom of opinion and expression; this right includes freedom to hold opinions without interference and to seek, receive and impart information and ideas through any media and regardless of frontiers. We agree, and we seek to uphold this and the other Articles of the Declaration.</p>
<nav>
  <%= link_to 'Wikileaks', 'http://wikileaks.org/' %>
</nav>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:heading, 'Contact Us') %>
<%= image_tag 'anonymous.gif', alt: 'We are anonymous, we are legion' %>

app/views/pages/help.html.erb
<% provide :title, 'Help'  %>
<% provide :heading, 'Help' %>
<%= image_tag 'http://i.imgur.com/VirPd.jpg', alt: 'Santorum is here to help' %>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:heading, 'Home Page') %>
<h2>ISYS100 Assignment 1 - Create a Website</h2>
<%= image_tag 'clapping.gif', alt: 'Congratulations! Assignment 1 is go.' %>

app/views/pages/references.html.erb
<% provide(:title, 'References') %>
<% provide(:heading, 'Assignment References') %>
<nav>
  <ul>
    <h4>Images</h4>
    <li>Gir image has been on my computer for ages but probably came from <a href="http://www.roomwithamoose.com">Room with a Moose</a></li>
    <li>Citizen Kane clapping gif comes courtesy of <a href="http://www.funnyordie.com/lists/30868d6681/gif-guide-clapping">Funny or Die</a></li>
    <h4>Javascript Widgets</h4>
    <li>Twitter Widget comes courtesy of <a href="http://www.twitter.com">Twitter</a></li>
    <li>The javascript quote widget came from <a href="http://www.codelifter.com/main/javascript/randomquote.shtml">Code Lifter</a> and the quotes came from <a href="http://en.wikipedia.org/wiki/Richard_Feynman">Richard Feynman</a>
  </ul>
</nav>

app/views/pages/report.html.erb
<% provide(:title, 'Report') %>
<% provide(:heading, 'Written Report') %>
<nav>
  <ul>
    <li><%= link_to 'Reason for Styling', anchor: 'reason' %></li>
    <li><%= link_to 'Site Design with Better Tech Access', anchor: 'style' %></li>
    <li><%= link_to 'Critique of an Admired Site', anchor: 'admire' %></li>
  </ul>
</nav>
<a name="reason"><h3>Reason for site styling</h3></a>
<p>Website design plays a large part in the usability of particular site. Colour schemes, content placement, ease of access, all add up to how nice the user experience is.</p>
<p>For this site the colour scheme has been specifically chosen to highlight the fact that a site that is clearly legible to most people could have some serious, unintended, drawbacks. This scheme in particular was chosen in part due to the fact that it can be harder for visually impaired people to see the content.</p>
<p>Layout considerations for the site included the use of white-space to draw the users focus into the specific areas that we want them focused on without clutter to distract them. Boxes were used for the styling of the site to enable a nice clean look with some space between the various information fields. Conventional wisdom holds that a typical site visitor is in a rush to get the information they're looking for and don't want to be wasting time. Instant gratification is the keyword for the eGeneration.</p>
<p>Placement of the links in the top right hand corner of the page has been deliberately done to aid with site navigation. The design here was to have a very easy to recognise system that is uniform across all the sites to enable users to have a very clear idea where site navigation links are and to not actually disrupt the exposure of the main content on the site.</p>
<p>Sans-serif was chosen for the font as a serif text can be harder to read from computer devices due to the lower resolution than real life. Serif fonts in book format are awesome but don't necessarily translate well to the screen. The actual font itself (Times) was chosen due to its ubiquitous nature on a multitude of computer and browser platforms. Additional benefit is provided by the common nature of the font in that it is a familiar font for most people and quite plain, this helps to stop the user from noticing the font more and the content less.</p><br />
<a name="sytle"><h3>Site Design with Better Tech Access</h3></a>
<p>The idea of having unlimited technological access to design this site would probably have to start with the ability to <a href="http://bash.org/?4281">stab people over the internet.</a></p>
<p>Site design with more advanced tech will very likely involve 3D interfaces, tactile feedback, increased utilisation of human senses to involve the user in a much more immersive experience. Something as simple as smelling a flower in a florist is a long way from seeing realisation on the internet.</p>
<p>Personalisation is something much more grounded in reality at the moment and is a very big thing for most of the giants on the internet today. Companies such as Google rely on the information they are able to gather from people for their main business model. The cost / benefit of such information gleaning for personalisation is a hotly debated topic with a number of pros and cons.</p>
<p>Another feature that is much more realisable with current tech is the ability for the site to be interactive. At present the ability for a site to be able to dynamically interact with a user is somewhat limited but as technology starts to advance (and data gleaned from users increases) this is also something that websites will hopefully be able to user to great effect.</p><br />
<a name="admire"><h3>Critique of an Admired Site</h3></a>
<p>Probably the site I admire most on the internet is a webcomic called <a href="http://www.xkcd.com">xkcd</a></p>
<p>The site isn't a glorious monument to social media, it's not a 2.0 interactive extravaganza, it is quite plain by the internets standards. This, however, is the perfect way to allow the content of the site to shine.</p>
<p>It has a nice clean layout with a very simple colour scheme. Bang in the middle of the screen, with the full focus of the user up access, is the webcomic. The artwork in its own right is also quite non-descript which only furthers to draw emphasis to the meat of the content in each comic.</p>
<p>At a larger scale the site as a whole has information that a user could need nicely organised into very clearly displayed and easy to navigate parcels. In fact the site built for this assignment has borrowed quite heavily from the layout of xkcd.</p>
<p>In brief; the clear, concise and carefully laid out nature of xkcd is why I admire it. </p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/pages/specifications.html.erb
<% provide :title, 'Specifications'  %>
<% provide :heading, 'Assignment Specifications' %>
<nav>
  <center>
    <ul>
      <li><%= link_to 'Getting Started', anchor: 'start' %></li>
      <li><%= link_to 'Must Haves', anchor: 'must' %></li>
      <li><%= link_to 'Report Specs', anchor: 'report' %></li>
      <li><%= link_to 'Submission', anchor: 'sub' %></li>
      <li><%= link_to 'Marking', anchor: 'mark' %></li>
    </ul>
  </center>
  <p>Your first assignment is to create a website on anything that is of interest to you. (Within reason :) The website will need to have minimum of 3 web pages. This means that you have an index page that will link to other pages and vice versa. 
  The key for this website to be a success is for you being able to demonstrate that you have used key design principles to create your site.</p>
  <a name="start"><h3>Creating Web Pages Using HTML</h3></a>
  <p>First create a new folder called Webpages and inside the folder create new web pages file called Mypage1.html and Mypage2.html etc.</p>
  <p>Open the file Mypage1.html in Notepad (programs  accessories  notepad) and write HTML code in the file. </p>
  <p>To find how to write HTML code read the tutorial and websites:</p>
  <ul>
    <li><%= link_to 'W3 Schools',  "http://www.w3schools.com/html/DEFAULT.asp" %></li>
    <li><%= link_to 'Web Monkey', "www.webmonkey.com" %></li>
    <li><%= link_to 'HTML Goodies', "www.htmlgoodies.com" %></li>
  </ul>
  <a name="must"><h3>Your web pages must include the following elements: </h3></a>
  <ul class="align_text">
    <li>Title / Header in all the pages</li><br />
    <li>Headings in all the page</li><br />
    <li>Reasonable amount of text in all the page</li><br />
    <li>Pictures</li><br />
    <li>Link to a web site on www [External Links]</li><br />
    <li>Link to Mypage2.html and Mypage3.html [Internal Links]</li><br />
    <li>Link to inside Mypage1.html (eg. Top or bottom of page) [Inline Links]</li><br />
    <li>A list [at least one]</li><br />
    <li>A table [at least one]</li><br />
    <li>References from where you took pictures and text [Source must be provided]</li><br />
    <li class="highlight">Please note that proper nesting of tags is a must</li><br />
    <li>Cascading Style Sheet (CSS):  The CSS should define the style of your webpages. All design elements used on your website should be defined and controlled via the CSS</li><br />
    <li>JavaScript: The purpose of Javascript is to add interactivity to your webpages. You must be able to demonstrate that you have incorporated at least 2 Javascript scripts within your website</li><br />
    <li>Your lecturer and practical teacher will assist you with these concepts and how best to use them within your website. <div class="highlight">Use of any software which aids in developing a website carries severe penalty</li><br />
  </ul>
  <a name="report"><h3>Report</h3></a>
  <ul class="align_text">
    <li>Part of the assignment is to write a report [600 - 1000 words] answering the questions specified below.</li><br />
    <li>Explain why you chose the CSS styles (color, font, spacing, theme, navigation, images, background) that you did. Discuss whether they make your website 'user friendly'</li>
    <li>If your technological ability were limitless, what else would you want to do with this web site? How would it look, what features would it have? How would it communicate better who you are and / or what you believe in</li>
    <li>Find one other web site that you admire and provide the URL. What specific elements do you think are admirable about the site (Design? Content? Layout? Overall impression? Cool technology?</li>
  </ul>
  <a name="sub"><h3>Submission</h3></a>
  <p>For your submission you will need your Twitter account. By now you would have added to your Twitter list your practical teacher's Twitter account. You will need to send a direct message to your practical teacher (not a 'tweet') with your final webpage link, your full name and StudentID before your practical class before the 16th Jan 2012 Your practical teacher will go through the assignment with you (in person) in the practical session also.</p>
  <a name="mark"><h3>Marking</h3></a>
  <p>Marks in this assignment are gained in two categories. <p>
  <p>The first category is the technical component of the assignment. Your website will be evaluated against the requirements specified above. Marks awarded are directly proportional to the amount of effort that is spent on the assignment. This means that you must spend extra time researching about html, css and javascript. Also remember that developing the website with 3 webpages is only a minimum specification. Note that in some cases half marks may be awarded.</p>
  <p>The second category is the ability to explain and discuss the submission. Your practical demonstrator will ask you questions about your submission and marks will be awarded on the basis of your ability to answer them. This section will always include an oral discussion with the demonstrator and will include a written discussion (You can consider the Report to be the main basis on your mark awarded for this category for Assignment 1).</p>
  <p>Note: We are serious about the requirement in the explanation and discussion category. It is not easy to obtain full marks in this category - only the very best students will do so.</p>
</nav>